In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv('../Data/Raw_Data/airbnb_dataset.csv')
df.head()

,listing_id,host_id,host_name,neighbourhood,city,room_type,property_type,price,minimum_nights,number_of_reviews,...,beds,bedrooms,bathrooms,guests,instant_bookable,cancellation_policy,host_response_rate,listing_status,device,payment_method
0,107345,10276,NaN,Bronx,New York City,Hotel room,apartment,213.62,27,51,...,NaN,-1.0,1 bath,8.0,T,strict_14_with_grace_period,NaN,NaN,NaN,PayPal
1,109454,5049,Emma,Manhattan,NYC,Private Room,Guest suite,289,15,38,...,-1.0,6.0,1.5,10.0,False,MODERATE,80,NaN,tablet,Card
2,119857,11567,Sophia,Manhattan,NYC,Private room,NaN,130.82,24,39,...,NaN,4.0,1 bath,NaN,t,strict,NaN,active,Mobile,Card
3,108591,5546,NaN,Queens,NYC,Entire home/apt,Apartment,36.43,13,49,...,3.0,4.0,2.5 baths,12.0,True,moderate,100%,Active,Mobile,NaN
4,117164,8693,Michael,Staten Island,New York,entire home/apt,Loft,271.74,21,41,...,10.0,3.0,1.5 bath,4.0,T,MODERATE,85 %,AVAILABLE,mobile,cash

In [4]:
df.shape

(20120, 27)

In [5]:
Cleaned_df = df.copy()

In [6]:
Cleaned_df=Cleaned_df.drop_duplicates()

In [7]:
Cleaned_df.duplicated().sum()

np.int64(0)

In [8]:
Cleaned_df.columns = (
    Cleaned_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ","_")
)

In [9]:
df.columns

Index(['listing_id', 'host_id', 'host_name', 'neighbourhood', 'city',
       'room_type', 'property_type', 'price', 'minimum_nights',
       'number_of_reviews', 'reviews_per_month', 'availability_365',
       'latitude', 'longitude', 'host_since', 'last_review', 'rating', 'beds',
       'bedrooms', 'bathrooms', 'guests', 'instant_bookable',
       'cancellation_policy', 'host_response_rate', 'listing_status', 'device',
       'payment_method'],
      dtype='str')

In [10]:
Cleaned_df['price'] = pd.to_numeric(
    Cleaned_df['price'],errors ='coerce'
)

In [11]:
Cleaned_df['bathrooms'] = pd.to_numeric(
    Cleaned_df['bathrooms'],errors ='coerce'
)

In [12]:
df.head()

,listing_id,host_id,host_name,neighbourhood,city,room_type,property_type,price,minimum_nights,number_of_reviews,...,beds,bedrooms,bathrooms,guests,instant_bookable,cancellation_policy,host_response_rate,listing_status,device,payment_method
0,107345,10276,NaN,Bronx,New York City,Hotel room,apartment,213.62,27,51,...,NaN,-1.0,1 bath,8.0,T,strict_14_with_grace_period,NaN,NaN,NaN,PayPal
1,109454,5049,Emma,Manhattan,NYC,Private Room,Guest suite,289,15,38,...,-1.0,6.0,1.5,10.0,False,MODERATE,80,NaN,tablet,Card
2,119857,11567,Sophia,Manhattan,NYC,Private room,NaN,130.82,24,39,...,NaN,4.0,1 bath,NaN,t,strict,NaN,active,Mobile,Card
3,108591,5546,NaN,Queens,NYC,Entire home/apt,Apartment,36.43,13,49,...,3.0,4.0,2.5 baths,12.0,True,moderate,100%,Active,Mobile,NaN
4,117164,8693,Michael,Staten Island,New York,entire home/apt,Loft,271.74,21,41,...,10.0,3.0,1.5 bath,4.0,T,MODERATE,85 %,AVAILABLE,mobile,cash

In [13]:
Cleaned_df['host_response_rate'] = (
    Cleaned_df['host_response_rate']
    .astype(str)
    .str.replace('%','',regex=False)
)
Cleaned_df['host_response_rate'] = pd.to_numeric(Cleaned_df['host_response_rate'],errors = 'coerce')

In [14]:
df.head()

,listing_id,host_id,host_name,neighbourhood,city,room_type,property_type,price,minimum_nights,number_of_reviews,...,beds,bedrooms,bathrooms,guests,instant_bookable,cancellation_policy,host_response_rate,listing_status,device,payment_method
0,107345,10276,NaN,Bronx,New York City,Hotel room,apartment,213.62,27,51,...,NaN,-1.0,1 bath,8.0,T,strict_14_with_grace_period,NaN,NaN,NaN,PayPal
1,109454,5049,Emma,Manhattan,NYC,Private Room,Guest suite,289,15,38,...,-1.0,6.0,1.5,10.0,False,MODERATE,80,NaN,tablet,Card
2,119857,11567,Sophia,Manhattan,NYC,Private room,NaN,130.82,24,39,...,NaN,4.0,1 bath,NaN,t,strict,NaN,active,Mobile,Card
3,108591,5546,NaN,Queens,NYC,Entire home/apt,Apartment,36.43,13,49,...,3.0,4.0,2.5 baths,12.0,True,moderate,100%,Active,Mobile,NaN
4,117164,8693,Michael,Staten Island,New York,entire home/apt,Loft,271.74,21,41,...,10.0,3.0,1.5 bath,4.0,T,MODERATE,85 %,AVAILABLE,mobile,cash

In [15]:
df.tail()

,listing_id,host_id,host_name,neighbourhood,city,room_type,property_type,price,minimum_nights,number_of_reviews,...,beds,bedrooms,bathrooms,guests,instant_bookable,cancellation_policy,host_response_rate,listing_status,device,payment_method
20115,111285,11257,Sophia,Brooklyn,New York,Shared room,Townhouse,68.76,365,44,...,1.0,1.0,3 baths,1.0,NaN,strict_14_with_grace_period,NaN,available,desktop,cash
20116,111965,8929,David,Bronx,New York,Private Room,Guest suite,69.01,19,30,...,NaN,5.0,1 bath,6.0,F,strict_14_with_grace_period,90%,Active,Desktop,Card
20117,105391,10739,Michael,Staten Island,New York,entire home/apt,apartment,280.07,12,42,...,10.0,-1.0,2,2.0,F,strict_14_with_grace_period,80,Active,desktop,cash
20118,100861,8325,John Smith,Brooklyn,NYC,Shared room,NaN,476.49,365,44,...,8.0,NaN,NaN,1.0,NaN,MODERATE,100%,available,Mobile,PayPal
20119,115796,5659,NaN,Queens,NYC,Private Room,Townhouse,84.16,3650,61,...,4.0,2.0,1 bath,3.0,f,strict,100%,available,Desktop,card

In [16]:
(Cleaned_df['host_response_rate'].dtype)

dtype('float64')

In [17]:
Cleaned_df['host_response_rate'].head(20)

0       NaN
1      80.0
2       NaN
3     100.0
4      85.0
5      80.0
6      80.0
7      80.0
8       NaN
9      95.0
10     85.0
11      NaN
12      NaN
13      NaN
14     95.0
15    100.0
16     85.0
17     85.0
18     80.0
19     80.0
Name: host_response_rate, dtype: float64

In [18]:
Cleaned_df['host_since'] = pd.to_datetime(Cleaned_df['host_since'],errors = "coerce")

In [19]:
Cleaned_df['last_review'] = pd.to_datetime(Cleaned_df['last_review'],errors = 'coerce')

In [20]:
pd.set_option('display.max_columns',None)

In [21]:
Categorical_columns = [
    'neighbourhood',
    'city',
    'room_type',
    'property_type',
    'instant_bookable',
    'cancellation_policy',
    'listing_status',
    'device',
    'payment_method'
]

In [22]:
for col in Categorical_columns:
    Cleaned_df[col] = Cleaned_df[col].str.strip().str.lower()

In [23]:
Cleaned_df.isnull().sum().sort_values(ascending = False)

bathrooms              13330
host_name               3605
bedrooms                3394
payment_method          3356
device                  3319
host_response_rate      3313
listing_status          3263
instant_bookable        2896
guests                  2731
property_type           2268
last_review             2000
price                   1992
beds                    1639
reviews_per_month       1600
rating                  1000
neighbourhood              0
host_id                    0
listing_id                 0
room_type                  0
number_of_reviews          0
minimum_nights             0
city                       0
host_since                 0
availability_365           0
latitude                   0
longitude                  0
cancellation_policy        0
dtype: int64

In [24]:
Cleaned_df['guests'] = (
    Cleaned_df['guests']
    .astype(str)
    .str.replace('%','',regex=False)
)
Cleaned_df['guests'] = pd.to_numeric(Cleaned_df['guests'],errors = 'coerce')

In [25]:
Cleaned_df['bathrooms'] = pd.to_numeric(
    Cleaned_df['bathrooms'],errors = 'coerce'
)

In [26]:
Cleaned_df['price'] = pd.to_numeric(
    Cleaned_df['price'],errors = 'coerce'
)

In [27]:
numeric_columns = [
    'price',
    'reviews_per_month',
    'rating',
    'beds',
    'bedrooms',
    'bathrooms',
    'guests',
    'host_response_rate'
]
for col in numeric_columns:
    Cleaned_df[col] = Cleaned_df[col].fillna(Cleaned_df[col].median())

In [28]:
categorical_columns = [
    'neighbourhood',
    'city',
    'room_type',
    'instant_bookable',
    'cancellation_policy',
    'listing_status',
    'device',
    'payment_method'
]
for col in categorical_columns:
    Cleaned_df[col] = Cleaned_df[col].fillna(Cleaned_df[col].mode()[0])

In [29]:
Cleaned_df['host_name'] = Cleaned_df['host_name'].fillna('unknown')

In [30]:
Cleaned_df['last_review'] = pd.to_datetime(Cleaned_df['last_review'],errors = 'coerce')

In [31]:
Cleaned_df.isnull().sum().sort_values(ascending = False)

property_type          2268
last_review            2000
host_id                   0
host_name                 0
neighbourhood             0
city                      0
room_type                 0
price                     0
minimum_nights            0
number_of_reviews         0
listing_id                0
reviews_per_month         0
availability_365          0
longitude                 0
latitude                  0
host_since                0
rating                    0
beds                      0
bedrooms                  0
bathrooms                 0
guests                    0
instant_bookable          0
cancellation_policy       0
host_response_rate        0
listing_status            0
device                    0
payment_method            0
dtype: int64

In [32]:
Cleaned_df[Cleaned_df['price'] <= 0]

,listing_id,host_id,host_name,neighbourhood,city,room_type,property_type,price,minimum_nights,number_of_reviews,reviews_per_month,availability_365,latitude,longitude,host_since,last_review,rating,beds,bedrooms,bathrooms,guests,instant_bookable,cancellation_policy,host_response_rate,listing_status,device,payment_method
656,110049,9887,Emma,staten island,new york,private room,condo,-50.0,7,42,3.43,323,40.795671,-74.078571,2022-06-13,2018-03-21,5.00,5.0,2.0,2.0,3.0,f,strict,95.0,active,desktop,paypal
11726,117013,9431,David,manhattan,new york,entire home/apt,apartment,-50.0,14,45,0.36,99,40.714501,-73.903029,2020-10-12,2018-12-27,3.97,7.0,6.0,1.5,5.0,t,flexible,80.0,active,desktop,paypal
13931,117745,9777,Michael,staten island,new york city,private room,house,-50.0,1,31,1.41,346,40.757055,-73.995893,2016-11-26,2022-02-09,4.57,5.0,6.0,1.5,8.0,f,strict,90.0,available,tablet,cash
17572,116289,8008,Michael,staten island,new york,entire home/apt,NaN,-50.0,20,53,0.51,14,40.767588,-73.934990,2025-01-27,2023-08-18,4.54,4.0,0.0,1.5,5.0,true,flexible,100.0,booked,desktop,paypal
20007,117869,7521,unknown,queens,nyc,entire home/apt,condo,-50.0,21,52,0.46,49,40.736182,-74.074768,2018-04-05,2015-06-08,4.34,-1.0,4.0,1.5,4.0,f,flexible,100.0,active,desktop,paypal

In [33]:
Cleaned_df = Cleaned_df[Cleaned_df['price']>0]

In [34]:
Cleaned_df[Cleaned_df['minimum_nights'] <= 0]

Empty DataFrame
Columns: [listing_id, host_id, host_name, neighbourhood, city, room_type, property_type, price, minimum_nights, number_of_reviews, reviews_per_month, availability_365, latitude, longitude, host_since, last_review, rating, beds, bedrooms, bathrooms, guests, instant_bookable, cancellation_policy, host_response_rate, listing_status, device, payment_method]
Index: []

In [35]:
Cleaned_df[(Cleaned_df['rating']<0) |(Cleaned_df['rating']>5)]

Empty DataFrame
Columns: [listing_id, host_id, host_name, neighbourhood, city, room_type, property_type, price, minimum_nights, number_of_reviews, reviews_per_month, availability_365, latitude, longitude, host_since, last_review, rating, beds, bedrooms, bathrooms, guests, instant_bookable, cancellation_policy, host_response_rate, listing_status, device, payment_method]
Index: []

In [36]:
Cleaned_df.dtypes

listing_id                      int64
host_id                         int64
host_name                         str
neighbourhood                     str
city                              str
room_type                         str
property_type                     str
price                         float64
minimum_nights                  int64
number_of_reviews               int64
reviews_per_month             float64
availability_365                int64
latitude                      float64
longitude                     float64
host_since             datetime64[us]
last_review            datetime64[us]
rating                        float64
beds                          float64
bedrooms                      float64
bathrooms                     float64
guests                        float64
instant_bookable                  str
cancellation_policy               str
host_response_rate            float64
listing_status                    str
device                            str
payment_method                    str
dtype: object

In [37]:
'duplicate row:',Cleaned_df.duplicated().sum()

('duplicate row:', np.int64(0))

In [38]:
Cleaned_df.isnull().sum()

listing_id                0
host_id                   0
host_name                 0
neighbourhood             0
city                      0
room_type                 0
property_type          2267
price                     0
minimum_nights            0
number_of_reviews         0
reviews_per_month         0
availability_365          0
latitude                  0
longitude                 0
host_since                0
last_review            2000
rating                    0
beds                      0
bedrooms                  0
bathrooms                 0
guests                    0
instant_bookable          0
cancellation_policy       0
host_response_rate        0
listing_status            0
device                    0
payment_method            0
dtype: int64

In [39]:
Cleaned_df['property_type'].value_counts(dropna = False)

property_type
apartment      4534
house          4428
NaN            2267
loft           2235
condo          2230
guest suite    2154
townhouse      2147
Name: count, dtype: int64

In [40]:
Cleaned_df['property_type'].unique()

<StringArray>
['apartment', 'guest suite', nan, 'loft', 'townhouse', 'house', 'condo']
Length: 7, dtype: str

In [41]:
Cleaned_df.duplicated().sum()

np.int64(0)

In [42]:
Cleaned_df = Cleaned_df.drop_duplicates()

In [43]:
Cleaned_df.duplicated().sum()

np.int64(0)

In [44]:
Cleaned_df.head()

,listing_id,host_id,host_name,neighbourhood,city,room_type,property_type,price,minimum_nights,number_of_reviews,reviews_per_month,availability_365,latitude,longitude,host_since,last_review,rating,beds,bedrooms,bathrooms,guests,instant_bookable,cancellation_policy,host_response_rate,listing_status,device,payment_method
0,107345,10276,unknown,bronx,new york city,hotel room,apartment,213.62,27,51,1.38,172,40.783428,-73.954349,2022-06-09,2015-07-05,3.82,4.0,-1.0,1.5,8.0,t,strict_14_with_grace_period,90.0,active,desktop,paypal
1,109454,5049,Emma,manhattan,nyc,private room,guest suite,289.00,15,38,0.22,112,40.599777,-74.045431,2017-07-20,NaT,3.66,-1.0,6.0,1.5,10.0,false,moderate,80.0,active,tablet,card
2,119857,11567,Sophia,manhattan,nyc,private room,NaN,130.82,24,39,3.76,260,40.660940,-73.910553,2018-06-10,2023-06-02,4.76,4.0,4.0,1.5,5.0,t,strict,90.0,active,mobile,card
3,108591,5546,unknown,queens,nyc,entire home/apt,apartment,36.43,13,49,10.15,217,40.729728,-74.042471,2020-02-23,2020-11-17,3.94,3.0,4.0,1.5,12.0,true,moderate,100.0,active,mobile,card
4,117164,8693,Michael,staten island,new york,entire home/apt,loft,271.74,21,41,1.67,229,40.720245,-73.884852,2024-07-11,2023-12-02,3.71,10.0,3.0,1.5,4.0,t,moderate,85.0,available,mobile,cash

In [45]:
Cleaned_df.tail()

,listing_id,host_id,host_name,neighbourhood,city,room_type,property_type,price,minimum_nights,number_of_reviews,reviews_per_month,availability_365,latitude,longitude,host_since,last_review,rating,beds,bedrooms,bathrooms,guests,instant_bookable,cancellation_policy,host_response_rate,listing_status,device,payment_method
20115,111285,11257,Sophia,brooklyn,new york,shared room,townhouse,68.76,365,44,2.73,286,40.651466,-73.936715,2019-11-22,2022-07-06,4.34,1.0,1.0,1.5,1.0,f,strict_14_with_grace_period,90.0,available,desktop,cash
20116,111965,8929,David,bronx,new york,private room,guest suite,69.01,19,30,2.65,321,40.660944,-74.002625,2019-07-18,2025-07-02,3.76,4.0,5.0,1.5,6.0,f,strict_14_with_grace_period,90.0,active,desktop,card
20117,105391,10739,Michael,staten island,new york,entire home/apt,apartment,280.07,12,42,2.53,311,40.780444,-73.971801,2023-11-23,2024-04-23,3.88,10.0,-1.0,2.0,2.0,f,strict_14_with_grace_period,80.0,active,desktop,cash
20118,100861,8325,John Smith,brooklyn,nyc,shared room,NaN,476.49,365,44,4.01,39,40.798953,-73.938145,2019-10-10,2015-06-08,4.34,8.0,3.0,1.5,1.0,f,moderate,100.0,available,mobile,paypal
20119,115796,5659,unknown,queens,nyc,private room,townhouse,84.16,3650,61,1.21,306,40.786081,-73.961519,2019-11-26,2016-09-06,4.15,4.0,2.0,1.5,3.0,f,strict,100.0,available,desktop,card

In [46]:
print('Rows:',Cleaned_df.shape[0])
print('columns:',Cleaned_df.shape[1])
print(Cleaned_df.head())
print(Cleaned_df.info())

Rows: 19995
columns: 27
   listing_id  host_id host_name  neighbourhood           city  \
0      107345    10276   unknown          bronx  new york city
1      109454     5049      Emma      manhattan            nyc
2      119857    11567    Sophia      manhattan            nyc
3      108591     5546   unknown         queens            nyc
4      117164     8693   Michael  staten island       new york

         room_type property_type   price  minimum_nights  number_of_reviews  \
0       hotel room     apartment  213.62              27                 51
1     private room   guest suite  289.00              15                 38
2     private room           NaN  130.82              24                 39
3  entire home/apt     apartment   36.43              13                 49
4  entire home/apt          loft  271.74              21                 41

   reviews_per_month  availability_365   latitude  longitude host_since  \
0               1.38               172  40.783428 -73.954349 2022-06-09
1               0.22               112  40.599777 -74.045431 2017-07-20
2               3.76               260  40.660940 -73.910553 2018-06-10
3              10.15               217  40.729728 -74.042471 2020-02-23
4               1.67               229  40.720245 -73.884852 2024-07-11

  last_review  rating  beds  bedrooms  bathrooms  guests instant_bookable  \
0  2015-07-05    3.82   4.0      -1.0        1.5     8.0                t
1         NaT    3.66  -1.0       6.0        1.5    10.0            false
2  2023-06-02    4.76   4.0       4.0        1.5     5.0                t
3  2020-11-17    3.94   3.0       4.0        1.5    12.0             true
4  2023-12-02    3.71  10.0       3.0        1.5     4.0                t

           cancellation_policy  host_response_rate listing_status   device  \
0  strict_14_with_grace_period                90.0         active  desktop
1                     moderate                80.0         active   tablet
2                       strict                90.0         active   mobile
3                     moderate               100.0         active   mobile
4                     moderate                85.0      available   mobile

  payment_method
0         paypal
1           card
2           card
3           card
4           cash
<class 'pandas.DataFrame'>
Index: 19995 entries, 0 to 20119
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   listing_id           19995 non-null  int64
 1   host_id              19995 non-null  int64
 2   host_name            19995 non-null  str
 3   neighbourhood        19995 non-null  str
 4   city                 19995 non-null  str
 5   room_type            19995 non-null  str
 6   property_type        17728 non-null  str
 7   price                19995 non-null  float64
 8   minimum_nights       19995 non-null  int64
 9   number_of_reviews    19995 non-null  int64
 10  reviews_per_month    19995 non-null  float64
 11  availability_365     19995 non-null  int64
 12  latitude             19995 non-null  float64
 13  longitude            19995 non-null  float64
 14  host_since           19995 non-null  datetime64[us]
 15  last_review          17995 non-null  datetime64[us]
 16  rating               19995 non-null  float64
 17  beds                 19995 non-null  float64
 18  bedrooms             19995 non-null  float64
 19  bathrooms            19995 non-null  float64
 20  guests               19995 non-null  float64
 21  instant_bookable     19995 non-null  str
 22  cancellation_policy  19995 non-null  str
 23  host_response_rate   19995 non-null  float64
 24  listing_status       19995 non-null  str
 25  device               19995 non-null  str
 26  payment_method       19995 non-null  str
dtypes: datetime64[us](2), float64(10), int64(5), str(10)
memory usage: 4.3 MB
None

In [47]:
Cleaned_df['property_type'] = Cleaned_df['property_type'].fillna('unknown')

In [49]:
Cleaned_df.head()

,listing_id,host_id,host_name,neighbourhood,city,room_type,property_type,price,minimum_nights,number_of_reviews,reviews_per_month,availability_365,latitude,longitude,host_since,last_review,rating,beds,bedrooms,bathrooms,guests,instant_bookable,cancellation_policy,host_response_rate,listing_status,device,payment_method
0,107345,10276,unknown,bronx,new york city,hotel room,apartment,213.62,27,51,1.38,172,40.783428,-73.954349,2022-06-09,2015-07-05,3.82,4.0,-1.0,1.5,8.0,t,strict_14_with_grace_period,90.0,active,desktop,paypal
1,109454,5049,Emma,manhattan,nyc,private room,guest suite,289.00,15,38,0.22,112,40.599777,-74.045431,2017-07-20,NaT,3.66,-1.0,6.0,1.5,10.0,false,moderate,80.0,active,tablet,card
2,119857,11567,Sophia,manhattan,nyc,private room,unknown,130.82,24,39,3.76,260,40.660940,-73.910553,2018-06-10,2023-06-02,4.76,4.0,4.0,1.5,5.0,t,strict,90.0,active,mobile,card
3,108591,5546,unknown,queens,nyc,entire home/apt,apartment,36.43,13,49,10.15,217,40.729728,-74.042471,2020-02-23,2020-11-17,3.94,3.0,4.0,1.5,12.0,true,moderate,100.0,active,mobile,card
4,117164,8693,Michael,staten island,new york,entire home/apt,loft,271.74,21,41,1.67,229,40.720245,-73.884852,2024-07-11,2023-12-02,3.71,10.0,3.0,1.5,4.0,t,moderate,85.0,available,mobile,cash

In [50]:
Cleaned_df.loc[Cleaned_df['bedrooms']<0,'bedrooms'] = Cleaned_df['bedrooms'].median()

In [51]:
Cleaned_df.head()

,listing_id,host_id,host_name,neighbourhood,city,room_type,property_type,price,minimum_nights,number_of_reviews,reviews_per_month,availability_365,latitude,longitude,host_since,last_review,rating,beds,bedrooms,bathrooms,guests,instant_bookable,cancellation_policy,host_response_rate,listing_status,device,payment_method
0,107345,10276,unknown,bronx,new york city,hotel room,apartment,213.62,27,51,1.38,172,40.783428,-73.954349,2022-06-09,2015-07-05,3.82,4.0,3.0,1.5,8.0,t,strict_14_with_grace_period,90.0,active,desktop,paypal
1,109454,5049,Emma,manhattan,nyc,private room,guest suite,289.00,15,38,0.22,112,40.599777,-74.045431,2017-07-20,NaT,3.66,-1.0,6.0,1.5,10.0,false,moderate,80.0,active,tablet,card
2,119857,11567,Sophia,manhattan,nyc,private room,unknown,130.82,24,39,3.76,260,40.660940,-73.910553,2018-06-10,2023-06-02,4.76,4.0,4.0,1.5,5.0,t,strict,90.0,active,mobile,card
3,108591,5546,unknown,queens,nyc,entire home/apt,apartment,36.43,13,49,10.15,217,40.729728,-74.042471,2020-02-23,2020-11-17,3.94,3.0,4.0,1.5,12.0,true,moderate,100.0,active,mobile,card
4,117164,8693,Michael,staten island,new york,entire home/apt,loft,271.74,21,41,1.67,229,40.720245,-73.884852,2024-07-11,2023-12-02,3.71,10.0,3.0,1.5,4.0,t,moderate,85.0,available,mobile,cash

In [52]:
Cleaned_df['bedrooms'].median()

np.float64(3.0)

In [53]:
Cleaned_df['city'] = Cleaned_df['city'].str.lower().str.strip()
Cleaned_df['city'] = Cleaned_df['city'].replace({
    'nyc':'new york',
    'new york city':'new york'
})

In [54]:
Cleaned_df['city'].unique()

<StringArray>
['new york']
Length: 1, dtype: str

In [55]:
Cleaned_df.loc[Cleaned_df['beds']<0,'beds'] = Cleaned_df['beds'].median()

In [56]:
print('Rows:',Cleaned_df.shape[0])
print('columns:',Cleaned_df.shape[1])
print(Cleaned_df.head())
print(Cleaned_df.info())

Rows: 19995
columns: 27
   listing_id  host_id host_name  neighbourhood      city        room_type  \
0      107345    10276   unknown          bronx  new york       hotel room
1      109454     5049      Emma      manhattan  new york     private room
2      119857    11567    Sophia      manhattan  new york     private room
3      108591     5546   unknown         queens  new york  entire home/apt
4      117164     8693   Michael  staten island  new york  entire home/apt

  property_type   price  minimum_nights  number_of_reviews  reviews_per_month  \
0     apartment  213.62              27                 51               1.38
1   guest suite  289.00              15                 38               0.22
2       unknown  130.82              24                 39               3.76
3     apartment   36.43              13                 49              10.15
4          loft  271.74              21                 41               1.67

   availability_365   latitude  longitude host_since last_review  rating  \
0               172  40.783428 -73.954349 2022-06-09  2015-07-05    3.82
1               112  40.599777 -74.045431 2017-07-20         NaT    3.66
2               260  40.660940 -73.910553 2018-06-10  2023-06-02    4.76
3               217  40.729728 -74.042471 2020-02-23  2020-11-17    3.94
4               229  40.720245 -73.884852 2024-07-11  2023-12-02    3.71

   beds  bedrooms  bathrooms  guests instant_bookable  \
0   4.0       3.0        1.5     8.0                t
1   4.0       6.0        1.5    10.0            false
2   4.0       4.0        1.5     5.0                t
3   3.0       4.0        1.5    12.0             true
4  10.0       3.0        1.5     4.0                t

           cancellation_policy  host_response_rate listing_status   device  \
0  strict_14_with_grace_period                90.0         active  desktop
1                     moderate                80.0         active   tablet
2                       strict                90.0         active   mobile
3                     moderate               100.0         active   mobile
4                     moderate                85.0      available   mobile

  payment_method
0         paypal
1           card
2           card
3           card
4           cash
<class 'pandas.DataFrame'>
Index: 19995 entries, 0 to 20119
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   listing_id           19995 non-null  int64
 1   host_id              19995 non-null  int64
 2   host_name            19995 non-null  str
 3   neighbourhood        19995 non-null  str
 4   city                 19995 non-null  str
 5   room_type            19995 non-null  str
 6   property_type        19995 non-null  str
 7   price                19995 non-null  float64
 8   minimum_nights       19995 non-null  int64
 9   number_of_reviews    19995 non-null  int64
 10  reviews_per_month    19995 non-null  float64
 11  availability_365     19995 non-null  int64
 12  latitude             19995 non-null  float64
 13  longitude            19995 non-null  float64
 14  host_since           19995 non-null  datetime64[us]
 15  last_review          17995 non-null  datetime64[us]
 16  rating               19995 non-null  float64
 17  beds                 19995 non-null  float64
 18  bedrooms             19995 non-null  float64
 19  bathrooms            19995 non-null  float64
 20  guests               19995 non-null  float64
 21  instant_bookable     19995 non-null  str
 22  cancellation_policy  19995 non-null  str
 23  host_response_rate   19995 non-null  float64
 24  listing_status       19995 non-null  str
 25  device               19995 non-null  str
 26  payment_method       19995 non-null  str
dtypes: datetime64[us](2), float64(10), int64(5), str(10)
memory usage: 4.3 MB
None

In [57]:
Cleaned_df.isnull().sum()

listing_id                0
host_id                   0
host_name                 0
neighbourhood             0
city                      0
room_type                 0
property_type             0
price                     0
minimum_nights            0
number_of_reviews         0
reviews_per_month         0
availability_365          0
latitude                  0
longitude                 0
host_since                0
last_review            2000
rating                    0
beds                      0
bedrooms                  0
bathrooms                 0
guests                    0
instant_bookable          0
cancellation_policy       0
host_response_rate        0
listing_status            0
device                    0
payment_method            0
dtype: int64

In [58]:
Cleaned_df.to_csv(
    'airbnb_cleaned.csv',
    index = False
)